// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WinFormsDtLib.Models;

namespace WinFormsDtLib.Models
{
    public partial interface IWinFormsDataContextProcedures
    {
        Task<List<GetManagerResult>> GetManagerAsync(int? EmployeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
