// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsDtLib.Models;

public partial class Manager
{
    public int Id { get; set; }

    public int? ManagerId { get; set; }

    public virtual Employee IdNavigation { get; set; }
}