// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WinFormsDtLib.Models;

namespace WinFormsDtLib.Models
{
    public partial class WinFormsDataContext
    {
        private IWinFormsDataContextProcedures _procedures;

        public virtual IWinFormsDataContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new WinFormsDataContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IWinFormsDataContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class WinFormsDataContextProcedures : IWinFormsDataContextProcedures
    {
        private readonly WinFormsDataContext _context;

        public WinFormsDataContextProcedures(WinFormsDataContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetManagerResult>> GetManagerAsync(int? EmployeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "EmployeeId",
                    Value = EmployeeId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetManagerResult>("EXEC @returnValue = [dbo].[GetManager] @EmployeeId = @EmployeeId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
